#include <stdio.h>
#include <math.h>

// Project Euler Problem Numer 2 
/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
						1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


int fibonacci() {
	int fib1,fib2,fib_out,count;
	int sum = 2; // Initialize the running sum for the first two elements
	fib1 = 1; // First element in fib sequence
	fib2 = 2; // Second element in fib sequence
	
	// While next term in fib sequence meets constraints...
	while(fib1+fib2 < 4000000) {
		// compute next term
		fib_out = fib1 + fib2;
		// next two lines advance the sequence
		fib1 = fib2;
		fib2 = fib_out;
		
		// If the new term is even add to the sum
		if(fib_out%2 ==0){
			sum = sum + fib_out;
		}
	}
	return sum;
}


int main(){
	int out;
	out = fibonacci();
	printf("The anser is %d\n",out);
	return 0;
}
